apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{storageclass}}-claim
  namespace: {{testproject}}
spec:
  accessModes:
  - ReadWriteMany
  resources:
     requests:
          storage: 1Gi
  storageClassName: {{storageclass}}
