---

- name: node check | set node as unscheduable
  shell: "oc --config=../kubeconfig manage-node {{hostname}} --schedulable=false"
  register: oc_get_node
  changed_when: 1==2
  failed_when: "'SchedulingDisabled' not in oc_get_node.stdout"
  delegate_to: localhost

- name: node check | see if pods are running on node
  shell: "oc --config=../kubeconfig adm drain {{hostname}} --delete-local-data --ignore-daemonsets  --force"
  register: oc_get_node
  changed_when: 1==2
  failed_when: "'error' in oc_get_node.stdout"
  delegate_to: localhost

- name: node check | reboot node
  reboot:

- name: node check | wait for node to appear as ready
  shell: "oc --config=../kubeconfig get nodes |grep -i {{hostname}}|grep -i Ready"
  register: oc_node_ready
  until: "'NotReady' not in oc_node_ready.stdout and 'Ready' in oc_node_ready.stdout"
  retries: 20
  delay: 2
  delegate_to: localhost

- name: node check | set node as scheduable
  shell: "oc --config=../kubeconfig manage-node {{hostname}} --schedulable=true"
  register: oc_node_up
  changed_when: 1==2
  failed_when: "'SchedulingDisabled' in oc_node_up.stdout"
  delegate_to: localhost

