apiVersion: v1
kind: Service
metadata:
  labels:
    app: nodejs-mongodb-example
    template: nodejs-mongodb-example
    template.openshift.io/template-instance-owner: fd78d1c2-7a1d-11e9-9f4c-525400a64696
  name: mongodb
  namespace: testing
spec:
  ports:
  - name: mongodb
    port: 27017
    protocol: TCP
    targetPort: 27017
  selector:
    name: mongodb
  sessionAffinity: None
  type: ClusterIP
