apiVersion: v1
kind: Service
metadata:
  annotations:
    description: Exposes and load balances the application pods
    service.alpha.openshift.io/dependencies: '[{"name": "mongodb", "kind": "Service"}]'
  labels:
    app: nginx
    template: nginx
    template.openshift.io/template-instance-owner: fd78d1c2-7a1d-11e9-9f4c-525400a64696
  name: nginx
  namespace: sanitytesting
spec:
  ports:
  - name: web
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    name: nginx
  sessionAffinity: None
  type: ClusterIP
