apiVersion: v1
data:
  parameters: eyJEQVRBQkFTRV9OQU1FIjoic2FtcGxlZGIiLCJEQVRBQkFTRV9TRVJWSUNFX05BTUUiOiJtb25nb2RiIiwiTUVNT1JZX0xJTUlUIjoiNTEyTWkiLCJNRU1PUllfTU9OR09EQl9MSU1JVCI6IjUxMk1pIiwiTU9OR09EQl9WRVJTSU9OIjoiMy40IiwiTkFNRSI6Im5vZGVqcy1tb25nb2RiLWV4YW1wbGUiLCJOQU1FU1BBQ0UiOiJvcGVuc2hpZnQiLCJOT0RFSlNfVkVSU0lPTiI6IjgiLCJTT1VSQ0VfUkVQT1NJVE9SWV9VUkwiOiJodHRwczovL2dpdGh1Yi5jb20vc2Nsb3JnL25vZGVqcy1leC5naXQifQ==
kind: Secret
metadata:
  name: nodejs-mongodb-example-parametersvrli3
  ownerReferences:
  - apiVersion: servicecatalog.k8s.io/v1beta1
    blockOwnerDeletion: false
    controller: false
    kind: ServiceInstance
    name: nodejs-mongodb-example-l6h5x
    uid: ac226a73-7a19-11e9-bd31-0a580a8001a3
  namespace: testing
type: Opaque
