---

- name: Create a project
  openshift_raw:
    api_version: v1
    kind: Project
    name: sanitytesting
    kubeconfig: "../kubeconfig"
    state: present

- name: prepare nginx yaml
  template:
    src: nginx.yaml
    dest: roles/create_project/files/nginx.yaml

- name: prepare route yaml
  template:
    src: nginxroute.yaml
    dest: roles/create_project/files/nginxroute.yaml

- name: deploy application | deploy nginx configmap
  openshift_raw:
    src: roles/create_project/files/nginxcm.yaml
    state: present
    kubeconfig: "../kubeconfig"

- name: deploy application | deploy nginx deploymentconfig
  openshift_raw:
    src: roles/create_project/files/nginx.yaml
    state: present
    kubeconfig: "../kubeconfig"

- name: deploy application | create nginx service
  openshift_raw:
    src: roles/create_project/files/nginxsvc.yaml
    state: present
    kubeconfig: "../kubeconfig"

- name: deploy application | create route for nginx
  openshift_raw:
    src: roles/create_project/files/nginxroute.yaml
    state: present
    kubeconfig: "../kubeconfig"

- name: check | pods are up
  shell: "oc get pods -n sanitytesting |grep -i nginx|grep -i Running"
  register: oc_get_pods
  until: "'Running' in oc_get_pods.stdout"
  retries: 60
  delay: 2
  delegate_to: {{groups['masters'] | first}}

- name: check | app answers via router
  uri:
    url: http://nginx-sanitytesting.{{appsdomain}}
  register: uri_check
  until: "'OK' in uri_check.msg"
  retries: 20
  delay: 2

- name: Delete a project
  openshift_raw:
    api_version: v1
    kind: Project
    name: sanitytesting
    kubeconfig: "../kubeconfig"
    state: absent
    kubeconfig: "../kubeconfig"
