---

- name: Create a project
  openshift_raw:
    api_version: v1
    kind: Project
    name: testing
    kubeconfig: "../kubeconfig"
    state: present

- name: deploy application | update nodejs is
  openshift_raw:
    src: roles/create_project/files/nodejsis.yaml
    state: present
    kubeconfig: "../kubeconfig"

- name: deploy application | deploy nginx
  openshift_raw:
    src: roles/create_project/files/nginx.yaml
    state: present
    kubeconfig: "../kubeconfig"

- name: deploy application | create nginx service
  openshift_raw:
    src: roles/create_project/files/nginxsvc.yaml
    state: present
    kubeconfig: "../kubeconfig"

- name: deploy application | create route for nginx
  openshift_raw:
    src: roles/create_project/files/nginxroute.yaml
    state: present
    kubeconfig: "../kubeconfig"

- name: check | pods are up
  shell: "oc get pods -n testing |grep -i nginx|grep -i Running"
  register: oc_get_pods
  until: "'Running' in oc_get_pods.stdout"
  retries: 60
  delay: 2

- name: check | app answers via router
  uri:
    url: http://nginx-testing.{{appsdomain}}
  register: uri_check
  until: "'OK' in uri_check.msg"
  retries: 20
  delay: 2

- name: Delete a project
  openshift_raw:
    api_version: v1
    kind: Project
    name: testing
    kubeconfig: "../kubeconfig"
    state: absent
    kubeconfig: "../kubeconfig"
