---

- hosts: masters
  gather_facts: false

  tasks:


  - name: copy kubeconfig
    fetch: 
      src: /root/.kube/config
      dest: ../kubeconfig
      flat: yes      

  - name: copy etcd.conf
    fetch:
      src: /etc/etcd/etcd.conf
      dest: ../etcd.conf
      flat: yes


- hosts: localhost
  gather_facts: false
  roles:
    - create_project
    - infra_check

- hosts: masters
  gather_facts: false
  serial: 1
  roles:
    - restart_nodes 

