---

- hosts: masters
  gather_facts: false

  tasks:


  - name: copy kubeconfig
    fetch: 
      src: /root/.kube/config
      dest: ../kubeconfig
      flat: yes      

  - name: copy etcd.conf
    fetch:
      src: /etc/etcd/etcd.conf
      dest: ../etcd.conf
      flat: yes

  - name: prepare admin user
    shell: oc adm policy add-scc-to-user privileged system:serviceaccount:default:default

  - name: prepare admin user
    shell: oc adm policy add-scc-to-group anyuid system:authenticated



- hosts: localhost
  gather_facts: false


  tasks:

  - name: Final Check | Check that all pods returned after tests
    shell: "oc --config=../kubeconfig get pods --all-namespaces|grep -v Running|grep -v NAMESPACE|grep -v NAME|grep -v READY| grep -v STATUS| grep -v RESTARTS| grep -v AGE"
    changed_when: 1==2
    register: finalstatus
    until: finalstatus.stdout_lines == ""
    retries: 0
    delay: 0

                                         
    

